### ISSUE TITLE
nios ii branch issue

### ISSUE THREAD

**Issue by halvbanan** [logisim-evolution/logisim-evolution#1758] opened 2023-06-11 19:49 UTC
when branching to a label it jumps to the location but it negates the pc addition so it minuses when its ahead and plusses when its behind the branch

**Comment by maehne** [comment] 2023-06-11 20:53
Thanks for the report @halvbanan! Could you please provide a reproducer (ZIP archive with `.circ` file plus assembly/ELF file) demonstrating the issue?

**Comment by halvbanan** [comment] 2023-06-12 06:25
[branchtest.zip](https://github.com/logisim-evolution/logisim-evolution/files/11718708/branchtest.zip)
here, it just branches ahead of target and behind target, it should be a nop-branch but it executes a branch-branch

**Comment by maehne** [comment] 2023-06-27 07:37
Thanks for the reproducer @halvbanan! @BFH-ktt1: Could you please have a look, as you wrote that code?

**Comment by BFH-ktt1** [comment] 2023-07-01 07:38
@halvbanan : Thanks a lot for this bug report. I can reproduce your problem and will look into a sollution

**Comment by BFH-ktt1** [comment] 2023-07-01 08:18
@halvbanan : The problem should be fixed by my latest PR. Closing this issue as resolved, please reopen if there is still a problem.

**Closed by BFH-ktt1** 2023-07-01 08:18 UTC
Labels: bug, pri std

**Comment by halvbanan** [comment] 2023-07-03 21:02
still is not fixed on the msi version, i redownloaded the latest version of x86-msi and ran the test that i gave on the zip folder, still does a branch-branch loop instead of branch-nop .

**Comment by davidhutchens** [comment] 2023-07-04 00:33
@halvbanan: You used the last release build. @BFH-ktt1 meant to say that the problem is fixed in our develop branch.

You can find the nightly build here:  [https://github.com/logisim-evolution/logisim-evolution/actions/workflows/nightly.yml](https://github.com/logisim-evolution/logisim-evolution/actions/workflows/nightly.yml)

For Windows, use the .msi artifact in the latest nightly build.
