### ISSUE TITLE
Command line arguments parser

### ISSUE THREAD

**Issue by MarcinOrlowski** [logisim-evolution/logisim-evolution#981] opened 2021-08-31 09:34 UTC
### Discussed in https://github.com/logisim-evolution/logisim-evolution/discussions/980

<div type='discussions-op-text'>

<sup>Originally posted by **BFH-ktt1** August 31, 2021</sup>
Currently the command-line parser in "Startup.java" is really "a mess" and not intelligent. It would be nice to modernize this parser such that it would also allow for long parameters like "--version" and their short ones "-v" (as proposed by @R3dstOne in #963).
Any ideas and any takers?</div>

<sup>Originally posted by **MarcinOrlowski** August 31, 2021</sup>
What about using i.e. https://commons.apache.org/proper/commons-cli/?
---

Work in progress:

- [x] Update localization strings (remove keys etc)
- [x] Add missing localization strings
- [x] Simplify main handling code. Separate methods per option?
- [x] Add support for positional args (file to load)
- [x] Add short switches for all available options

**Comment by MarcinOrlowski** [comment] 2021-08-31 09:54
The side effect of using commons-cli is that we can have `--xxx` and `-x` options but not `-xxx` so that will be incompatible change. Still I'd go for it because `-xxx` is not standard approach anyway

**Comment by maehne** [comment] 2021-08-31 10:11
@MarcinOrlowski: IMHO, this is a duplicate of issue #963 and we should discuss your proposal there.

**Comment by MarcinOrlowski** [comment] 2021-08-31 11:01
#963 is related but not really a dupe. Also I already have args almost ported to commons CLI so I can take this one.

**Comment by MarcinOrlowski** [comment] 2021-08-31 12:14
#983 is early version of replacement CLI arg parsing code. Still WiP but PTAL

@BFH-ktt1 @R3dst0ne @maehne @davidhutchens

**Comment by BFH-ktt1** [comment] 2021-09-04 07:00
@MarcinOrlowski : can we close this one, as it is merged and we have other issues addressing the details?

**Closed** 2021-09-04 08:20 UTC
