### ISSUE TITLE
Reload Library not working

### ISSUE THREAD

**Issue by RomaricKc1** [logisim-evolution/logisim-evolution#1525] opened 2022-08-23 21:51 UTC
I found this issue after I included a sub-circuit as a library. It is set in a folder on the left-side navigation.

When modifications are made on the sub-circuit (which is running on another instance of Logisim), the reload library on the main circuit does not reload it. And if you hit ```Ctrl+S``` to save, you get an error saying: Window title: ```File error``` ```'component_name' component not found```.
After a close and restart of the project, you have to place the component on the main circuit again. Thankfully after that, the component comes with the updates.

It would be great if the reload does not require a  ```close and open``` of the main project and ```component placement``` again.

**Comment by BFH-ktt1** [comment] 2022-08-24 05:51
Closing as duplicate of #1424

**Closed by BFH-ktt1** 2022-08-24 05:51 UTC
