### ISSUE TITLE
Shifters in Verilog

### ISSUE THREAD

**Issue by EmperorPenguin18** [logisim-evolution/logisim-evolution#1425] opened 2022-03-31 23:02 UTC
When I synthesize to verilog, Shifter_2_bit.v, Shifter_32_bit.v and Shifter_64_bit.v all are missing a semicolon in the last assign statement.

**Comment by maehne** [comment] 2022-04-01 07:06
Thanks for reporting! The HDL code generation underwent last year a substantial reimplementation and, unfortunately, introduced some smaller bugs. On the VHDL side, these were found relatively quickly, but Verilog is used less on our side.

**Comment by BFH-ktt1** [comment] 2022-04-04 06:11
@EmperorPenguin18 , I confirm this bug, and also found another one where the stage results had the wrong name.

**Comment by BFH-ktt1** [comment] 2022-04-05 04:55
Please try the nightly build to see if the problem is fixed. Closing for now, please reopen when the problem persists.

**Closed by BFH-ktt1** 2022-04-05 04:55 UTC
Labels: bug, pri +1, investigating, all OS, good first issue
