### ISSUE TITLE
Message relating to Logisim Evolution during any flatpak update operation

### ISSUE THREAD

**Issue by neildarlow** [logisim-evolution/logisim-evolution#678] opened 2021-06-16 10:14 UTC
Whenever I update flatpaks from the command line I see the following output. I have no idea whether this is a packaging issue for Logisim Evolution.

> Wrong namespace on document element in '/var/lib/flatpak/exports/share/mime/packages/com.github.reds.LogisimEvolution.xml' (should be http://www.freedesktop.org/standards/shared-mime-info)

OS: fedora Silverblue 34
Flatpak: flatpak-1.10.2-3.fc34.x86_64

**Comment by MarcinOrlowski** [comment] 2021-06-16 11:16
Looks like wrong icon reference. Comes from [LogisimEvolution.desktop](https://github.com/logisim-evolution/logisim-evolution/blob/374a72318ecd0c16b7c077a2260753a1ffc2861c/support/Flatpak/com.github.reds.LogisimEvolution.desktop#L6)

**Comment by MarcinOrlowski** [comment] 2021-06-30 11:13
@neildarlow do you still have this issue? I just installed LS via flatpak and see no problems. If you still face this message, can you provide more details so I can try to reproduce?

@BFH-ktt1 do you maintain Flatpak page of LS?

**Comment by MarcinOrlowski** [comment] 2021-06-30 11:27
Because I see Flathub entry is sourced from this repo: https://github.com/flathub/com.github.reds.LogisimEvolution - is it related or 3rd party (members' nicks tell me nothing)?

**Comment by maehne** [comment] 2021-06-30 21:47
The flatpak was created by @TheEvilSkeleton and discussed in detail in issue #448.

**Comment by MarcinOrlowski** [comment] 2021-06-30 22:04
@TheEvilSkeleton could you please update the Flathub entry's description to match this landing page: https://github.com/logisim-evolution/logisim-evolution/tree/develop as (at least form me) what sticks out in current one is "and recently the development has been officially stopped." which is bad. Also if you could update the screenshot to one of https://github.com/logisim-evolution/logisim-evolution/tree/develop/docs/img it would be great.

Also can you please correct this entry:

> Developer
> REDS institute

@maehne am I correct that for now `support/Flatpak` can be removed?

@BFH-ktt1 shouldn't we have snap/flatpak packages under our control?

**Comment by maehne** [comment] 2021-06-30 22:15
> @maehne am I correct that for now `support/Flatpak` can be removed?

No, see [this message](https://github.com/logisim-evolution/logisim-evolution/issues/448#issuecomment-749684001) by @TheEvilSkeleton.

> @BFH-ktt1 shouldn't we have snap/flatpak packages under our control?

Ideally yes and I think @BFH-ktt1 has at least maintain rights for the associated repository. However, our knowledge and bandwidth is limited for maintaining all the different kind of packages. Also, manually building them on the different platforms for a release also costs time. We should probably strive for creating these packages as much as possible automatically using, e.g., GitHub Actions. As with many things, we are lacking time and knowledge to work this aspect. So help is welcome.

**Comment by MarcinOrlowski** [comment] 2021-06-30 22:22
Ok, I created #743 for that. 

I am also going to close this ticket as a) it works for me now, b) if it does not for OP then it should currently be reported here: https://github.com/flathub/com.github.reds.LogisimEvolution

**Closed by MarcinOrlowski** 2021-06-30 22:22 UTC
Labels: Linux, help wanted
