### ISSUE TITLE
Custom subcircuit appearance not shown

### ISSUE THREAD

**Issue by psen1** [logisim-evolution/logisim-evolution#1919] opened 2023-11-30 22:20 UTC
Hi there,

I'm a total n00b to Logisim and I'm using v. 3.8.0. I'm trying to edit the appearance of a subcircuit (using "Edit Circuit Appearance") to make it look different, but for some reason it shows up as the default appearance every time I go to place it somewhere else. 

I'm not sure what I'm doing wrong. I don't see any kind of "Save" or "Apply" button to make sure that what I have in the "Edit Circuit Appearance" canvas is what I get when I try to place the subcircuit. In fact, when I go back to that canvas, I see the edits I made, which makes me think they have been applied yet they don't show up when I try to use that component.

I've looked around and saw that some versions (3.7.*) had some problems with this but it doesn't seem to be an issue for 3.8.0. Any suggestions on what I'm doing wrong? This seems like a pretty straightforward task.

Thanks!

**Comment by davidhutchens** [comment] 2023-12-01 01:21
You need to set the appearance property to Custom. This is a duplicate of #1780. As noted there, it would be nice if it were set automatically when you edit the appearance.

**Closed** 2023-12-01 13:52 UTC
Labels: duplicate

**Comment by goofyseeker311** [comment] 2026-08-10 20:27
I dont seem to find how a sub-circuit component appearance can be set to anything else than the current very large block appearance. at least this is not clear if the settings feature is there. the logisim classic style minimal size component would be the best in general.

**Comment by davidhutchens** [comment] 2026-08-11 01:50
@goofyseeker311: I described how to do this in v4.1.0 in #2370. The method gets around the flaky interface behavior.

The best solution is to get the Nightly, which fixes the messy behavior, and then double click on the subcircuit to show it in the canvas. The Appearance attribute for the circuit can then be set.

You can also set it to custom and design your own appearance with the appearance editor (box with slash icon in upper left).

**Comment by goofyseeker311** [comment] 2026-08-11 02:28
I'm fine with 4.1 until next release. I just remember 4.0 and 4.1 experience with appearances doing nothing. so needs to be extra clear to be usable.
