### ISSUE TITLE
Component's font size is weird

### ISSUE THREAD

**Issue by quantrpeter** [logisim-evolution/logisim-evolution#1637] opened 2023-01-13 10:18 UTC
hi all, Component's font size is wried. 27 inch monitor with 4k

![Screenshot from 2023-01-13 18-17-36](https://user-images.githubusercontent.com/50471577/212296343-8bf68857-15fd-4e60-9866-2a7d13062307.png)

**Comment by maehne** [comment] 2023-01-13 12:50
This is a duplicate of issue #1452. A workaround is to reduce the screen resolution to Full HD 1920 x 1080. We don't have yet a fix for it. I'll close this issue. Please follow issue #1452 to track its evolution. PRs are welcome. @BFH-ktt1 and myself currently don't have much time at disposal for Logisim-evolution, as we are busy finalising the autumn term.

**Closed as completed** 2023-01-13 12:51 UTC
Labels: duplicate
