### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by TheEvilSkeleton** [logisim-evolution/logisim-evolution#447] opened 2020-11-13 19:50 UTC
Hello, `logisim-evolution` doesn't show up in the `Logisim` topic: https://github.com/topics/logisim. I just wanted to let you know that more people will find this software when topics get added.

Here are more Topics that I recommend to add: `education` `circuit` `circuits` `digital-circuit` `digital-circuits` `simulator` `logic`

**Comment by MarcinOrlowski** [comment] 2021-06-10 08:35
Indeed. But that can be easily addressed by editing repo topics: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/classifying-your-repository-with-topics

@maehne

**Comment by BFH-ktt1** [comment] 2021-06-10 09:02
I added the topics. When we require some others, please let me know. I'm closing the issue, please reopen if you think that the issue is not resolved

**Closed by BFH-ktt1** 2021-06-10 09:02 UTC

**Comment by MarcinOrlowski** [comment] 2021-06-10 14:16
I think you want to add `logisim` topic too

**Comment by maehne** [comment] 2021-06-11 14:05
`logisim` was added as a topic.
