### ISSUE TITLE
fatal error : optimizing altera project

### ISSUE THREAD

**Issue by shakirja** [logisim-evolution/logisim-evolution#1615] opened 2022-12-26 12:11 UTC
![image](https://user-images.githubusercontent.com/121437256/209547462-c63ffc2f-6d60-466e-93d5-c4f2001d8a9d.png)
I want to download my circuit on FPGA (DE10-Lite) and this error comes up.

**Comment by maehne** [comment] 2022-12-26 12:51
Which exact version of Logisim-evolution are you using and on which platform? Please, provide also a `.circ` file exposing the issue with instructions what circuit needs to be synthesised. The error you are observing is typically triggered by badly generated HDL and this heavily depends on the structure of your circuit.

**Comment by shakirja** [comment] 2022-12-26 17:57
[A3.2_2045880.zip](https://github.com/logisim-evolution/logisim-evolution/files/10304394/A3.2_2045880.zip)

This is my circuit, I am pretty sure that the problem is related to the demultiplexers. My logisim version is 3.7.2 on Windows 10 Pro

**Comment by maehne** [comment] 2022-12-27 09:24
The cause might be issue #1360, which is already fixed in [Logisim-evolution 3.8.0](https://github.com/logisim-evolution/logisim-evolution/releases/tag/v3.8.0). Please try and provide feedback!

**Comment by shakirja** [comment] 2022-12-28 07:39
I just downloaded 3.8.0 and faced the same problem

**Comment by maehne** [comment] 2022-12-28 10:12
For me, synthesis of your `main` circuit already fails earlier due to a net with multiple drivers: You did connect a constant `0` to output `Cout` of `EightBit_ALU`. Please, fix also all warnings due to unconnected input and splitter with unconnected fan-out pins.

At least, I am now able to reproduce your issue:

```
Info (12127): Elaborating entity "logisimTopLevelShell" for the top level hierarchy
Info (12128): Elaborating entity "logisimTickGenerator" for hierarchy "logisimTickGenerator:BASE_0" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/toplevel/logisimTopLevelShell_behavior.vhd Line: 65
Info (12128): Elaborating entity "LogisimClockComponent" for hierarchy "LogisimClockComponent:BASE_1" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/toplevel/logisimTopLevelShell_behavior.vhd Line: 71
Warning (10445): VHDL Subtype or Type Declaration warning at LogisimClockComponent_behavior.vhd(62): subtype or type has null range File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/base/LogisimClockComponent_behavior.vhd Line: 62
Info (12128): Elaborating entity "main" for hierarchy "main:CIRCUIT_0" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/toplevel/logisimTopLevelShell_behavior.vhd Line: 83
Warning (10036): Verilog HDL or VHDL warning at main_behavior.vhd(196): object "s_logisimNet45" assigned a value but never read File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 196
Warning (10036): Verilog HDL or VHDL warning at main_behavior.vhd(206): object "s_logisimNet60" assigned a value but never read File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 206
Warning (10036): Verilog HDL or VHDL warning at main_behavior.vhd(207): object "s_logisimNet61" assigned a value but never read File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 207
Info (12128): Elaborating entity "OR_GATE_8_INPUTS" for hierarchy "main:CIRCUIT_0|OR_GATE_8_INPUTS:GATES_1" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 353
Info (12128): Elaborating entity "AND_GATE" for hierarchy "main:CIRCUIT_0|AND_GATE:GATES_2" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 365
Info (12128): Elaborating entity "OR_GATE" for hierarchy "main:CIRCUIT_0|OR_GATE:GATES_3" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 371
Info (12128): Elaborating entity "Demultiplexer_8" for hierarchy "main:CIRCUIT_0|Demultiplexer_8:PLEXERS_4" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 377
Info (12128): Elaborating entity "Demultiplexer_bus_8" for hierarchy "main:CIRCUIT_0|Demultiplexer_bus_8:PLEXERS_5" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 390
Info (12128): Elaborating entity "Multiplexer_bus_8" for hierarchy "main:CIRCUIT_0|Multiplexer_bus_8:PLEXERS_6" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 404
Info (12128): Elaborating entity "Multiplexer_bus_2" for hierarchy "main:CIRCUIT_0|Multiplexer_bus_2:PLEXERS_8" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 432
Info (12128): Elaborating entity "LogisimCounter" for hierarchy "main:CIRCUIT_0|LogisimCounter:MEMORY_9" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 440
Info (12128): Elaborating entity "REGISTER_FLIP_FLOP" for hierarchy "main:CIRCUIT_0|REGISTER_FLIP_FLOP:Control_Register" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 455
Info (12128): Elaborating entity "REGISTER_FLIP_FLOP" for hierarchy "main:CIRCUIT_0|REGISTER_FLIP_FLOP:MEMORY_11" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 465
Info (12128): Elaborating entity "EightBit_ALU" for hierarchy "main:CIRCUIT_0|EightBit_ALU:EightBit_ALU_1" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/main_behavior.vhd Line: 550
Info (12128): Elaborating entity "OneBit_ALU" for hierarchy "main:CIRCUIT_0|EightBit_ALU:EightBit_ALU_1|OneBit_ALU:OneBit_ALU_5" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/EightBit_ALU_behavior.vhd Line: 88
Info (12128): Elaborating entity "Multiplexer_4" for hierarchy "main:CIRCUIT_0|EightBit_ALU:EightBit_ALU_1|OneBit_ALU:OneBit_ALU_5|Multiplexer_4:PLEXERS_3" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/OneBit_ALU_behavior.vhd Line: 115
Info (12128): Elaborating entity "FullAdder" for hierarchy "main:CIRCUIT_0|EightBit_ALU:EightBit_ALU_1|OneBit_ALU:OneBit_ALU_5|FullAdder:ARITH_5" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/OneBit_ALU_behavior.vhd Line: 133
Info (12128): Elaborating entity "FullSubtractor" for hierarchy "main:CIRCUIT_0|EightBit_ALU:EightBit_ALU_1|OneBit_ALU:OneBit_ALU_5|FullSubtractor:ARITH_6" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/circuit/OneBit_ALU_behavior.vhd Line: 141
Info (12128): Elaborating entity "LedArrayLedDefault" for hierarchy "LedArrayLedDefault:array0" File: C:/Users/mht1/logisim_evolution_workspace/A3.2_2045880/main/vhdl/toplevel/logisimTopLevelShell_behavior.vhd Line: 91
Internal Error: Sub-system: INFER, File: /quartus/synth/infer/infer_ram_inference.cpp, Line: 7103
write_address_width == static_cast<unsigned int>(m_write_address_a_dff_d_iterm_vec.size())
Stack Trace:
    0x12c22: OPT_RAM_POTENTIAL_CANDIDATE::find_write_address_decoder + 0x1d2 (SYNTH_INFER)
    0x126e1: OPT_RAM_POTENTIAL_CANDIDATE::find_ram_write_logic + 0x121 (SYNTH_INFER)
     0x64aa: OPT_RAM_INFERENCE::check_ram_bit + 0x9a (SYNTH_INFER)
     0x61a6: OPT_RAM_INFERENCE::find_ram_slice_from_mux + 0x256 (SYNTH_INFER)
     0x5e20: OPT_RAM_INFERENCE::find_ram_block + 0xb0 (SYNTH_INFER)
     0x5998: OPT_RAM_INFERENCE::try_to_infer_from_mux + 0x88 (SYNTH_INFER)
     0x5c7b: OPT_RAM_INFERENCE::infer_ram_blocks + 0xfb (SYNTH_INFER)
    0x3e82a: RTL_SCRIPT::call_ram_rom_fns + 0x346 (SYNTH_OPT)
    0x3be00: RTL_SCRIPT::call_named_function + 0x590 (SYNTH_OPT)
    0x40110: RTL_SCRIPT::process_script + 0x4f4 (SYNTH_OPT)
    0x41039: opt_process_netlist_scripted + 0x7a5 (SYNTH_OPT)
    0x39dda: RTL_ROOT::process_sgate_netlist + 0x196 (SYNTH_OPT)
   0x157fbd: SGN_SYNTHESIS::high_level_synthesis + 0x17d (synth_sgn)
   0x15897d: SGN_SYNTHESIS::process_current_stage + 0x20d (synth_sgn)
    0xc3a7d: SGN_EXTRACTOR::synthesize_partition + 0x18d (synth_sgn)
    0xc367f: SGN_EXTRACTOR::synthesis + 0x1ff (synth_sgn)
    0xc37e4: SGN_EXTRACTOR::synthesis_and_post_processing + 0xc4 (synth_sgn)
    0x13350: sgn_qic_full + 0x2a0 (synth_sgn)
     0x4351: qsyn_execute_sgn + 0x131 (quartus_map)
    0x13f9c: QSYN_FRAMEWORK::execute_core + 0x12c (quartus_map)
    0x13aa6: QSYN_FRAMEWORK::execute + 0x496 (quartus_map)
    0x112bc: qexe_do_normal + 0x1ec (comp_qexe)
    0x16142: qexe_run + 0x432 (comp_qexe)
    0x16e51: qexe_standard_main + 0xc1 (comp_qexe)
    0x1b08b: qsyn_main + 0x51b (quartus_map)
    0x12e98: msg_main_thread + 0x18 (CCL_MSG)
    0x1467e: msg_thread_wrapper + 0x6e (CCL_MSG)
    0x16660: mem_thread_wrapper + 0x70 (ccl_mem)
    0x12761: msg_exe_main + 0xa1 (CCL_MSG)
    0x29872: __tmainCRTStartup + 0x10e (quartus_map)
    0x126bc: BaseThreadInitThunk + 0x1c (KERNEL32)
    0x5dfb7: RtlUserThreadStart + 0x27 (ntdll)

End-trace
```

@BFH-ktt1: Could you please have a look what part of the generated HDL is causing the internal Quartus Prime error?

**Comment by BFH-ktt1** [comment] 2023-01-03 13:48
@shakirja , @maehne : This is really an interesting one, both VHDL and Verilog trigger the same behavior in Quartus 18.1 and 21.1: `Internal Error: Sub-system: INFER, File: /quartus/synth/infer/infer_ram_inference.cpp, Line: 7103`

Looking at the generated HDL I cannot find any error. Using YOSYS, the verilog synthesises perfectly.

I guess that we have triggered a bug in Quartus....

Solution to the problem: remove the dmux that goes from the ALU to R0...R7 and connect directly the R from the ALU to R0..R7. Due to the write-enables on the registers this does not change functionality, and with this "patch" we do not trigger the problem.

Closing this issue as solved, as it does not seem to be a logisim related bug. Please reopen if you feel that there is more to it.

**Closed by BFH-ktt1** 2023-01-03 13:48 UTC
Labels: bug, pri std, investigating, linux, windows

**Comment by maehne** [comment] 2023-01-03 15:15
@shakirja and @BFH-ktt1: If this issue is reproducible with a current Quartus release and it can be reproduced with an ideally stripped-down Verilog and VHDL test case, it is probably worth reporting this issue to Intel.

**Comment by goofyseeker311** [comment] 2026-07-23 10:40
this bug is still in v4.1.0 on win11. a simple constant to output to led mapping circuit works with builtin max1000, but when using my custom arrow_sockit fpga, this error pops up. also the same device programming works perfectly from quartus prime 25.1 lite. so the problem is with a custom fpga definition in logisim evolution. or something that kind of issue.

working with max1000:
<img width="1584" height="946" alt="Image" src="https://github.com/user-attachments/assets/b3e38d50-5824-4cf0-a059-16fe7b8cbef9" />

not working with arrow sockit:
<img width="961" height="839" alt="Image" src="https://github.com/user-attachments/assets/a90f787b-42ed-4cec-8c7d-207ee7854dab" />

[fpgatesting3.zip](https://github.com/user-attachments/files/30303427/fpgatesting3.zip)
[ARROW_SOCKIT.xml](https://github.com/user-attachments/files/30303835/ARROW_SOCKIT.xml)

side note: fpga editor sometimes fails to save other than an xml header.


edit: in my case, the console says my part name is illegal. fixed by finding out what the legal name is.

**Comment by goofyseeker311** [comment] 2026-07-23 13:49
also while now arrow sockit custom fpga board works fully, terasic de10 nano does not work while downloading, because of some wrong jtag id chain issues in the script.

<img width="702" height="594" alt="Image" src="https://github.com/user-attachments/assets/da778650-4e1d-4aeb-b536-363979fa7b1a" />

edit: this was fixed with the cpld/fpga location in the fpga board editor jtag settings.

**Comment by maehne** [comment] 2026-07-27 23:02
@goofyseeker311: Your screenshots and comments do not provide enough context to judge whether your issues are really the same as reported in this thread. Please, provide at least the output from the Console tab. Also make sure to not mix several issues into one report to ensure they can be treated individually.
