### ISSUE TITLE
TTL model woes: 74139 has inverted output logic, 7485 HDL generator outputs the wrong HDL code.

### ISSUE THREAD

**Issue by raps500** [logisim-evolution/logisim-evolution#1334] opened 2021-12-20 12:11 UTC
These findings apply to version 3.7.2:

The 74139 model has inverted logic, when an output is selected it should be at 0 and the others at 1:
```
    for (var i = 0; i < 4; i++) {
      final var val = enabled ? (outputPortStates[A + B][i] == 1 ? Value.TRUE : Value.FALSE) : Value.TRUE;
      state.setPort(mapPort(outPorts[i]), val, DELAY);
    }

```

The 7485 HDL generator outputs wrong HDL kind: if verilog it outputs VHDL and vice-versa:

`    if (Hdl.isVerilog()) {
      contents.addVhdlKeywords().add("""
            oppA   <= A3&A2&A1&A0;
            oppB   <= B3&B2&B1&B0;
            gt     <= '1' {{when}} unsign`

**Comment by maehne** [comment] 2021-12-31 09:23
@MarcinOrlowski: Could you maybe have a look to this issue?

**Comment by MarcinOrlowski** [comment] 2022-01-01 02:05
@raps500 can you please verify the issue is still present in latest stable or even develop build?

**Comment by raps500** [comment] 2022-01-02 12:50
As of 02.01.2022, both the main and develop branches still have both bugs, is there any other branch/version I can test ? The last activity on the nighty was 11 days ago.

**Comment by MarcinOrlowski** [comment] 2022-01-02 13:09
`develop` is development head, so that's sufficient. Thanks

**Comment by quick0831** [comment] 2022-03-20 16:41
I just try to do some experiment on 74139

[74LS139 datasheet](https://www.futurlec.com/74LS/74LS139.shtml)

Screenshot of the datasheet:
![image](https://user-images.githubusercontent.com/44318486/159172700-f1963b7d-017e-4e3d-a88a-60a8eae49155.png)
![image](https://user-images.githubusercontent.com/44318486/159172839-0d013282-8613-40b0-b4b3-147a1a874d02.png)

Test Circuit:
![image](https://user-images.githubusercontent.com/44318486/159172682-b94810a4-4a67-49b3-992b-086898d906ba.png)

Timing Diagram:
![image](https://user-images.githubusercontent.com/44318486/159172756-27bcb6d6-d929-4577-95ff-02394291c172.png)

**Comment by quick0831** [comment] 2022-03-20 16:43
Seems like the inputs are ok
only need to invert the output

**Comment by quick0831** [comment] 2022-03-20 16:56
Sorry I missed that.
I also checked the [datasheet](https://www.ti.com/product/SN74LS139A) mentioned in code.

It still said the same thing

![image](https://user-images.githubusercontent.com/44318486/159173485-33fec50a-e84f-497f-a14e-2ac39d842da3.png)

(I tested in `develop` branch)

**Comment by quick0831** [comment] 2022-03-20 17:07
I tried to put some fix (tested with same *.circ file)
![image](https://user-images.githubusercontent.com/44318486/159174042-9b862b3b-b804-44f0-a490-3dfe5f6db55f.png)

better

**Comment by quick0831** [comment] 2022-03-24 09:28
https://github.com/logisim-evolution/logisim-evolution/blob/master/src/main/java/com/cburch/logisim/std/ttl/Ttl7485HdlGenerator.java#L59-L59

For this line mentioned by OP, it should be changed to `Hdl.isVhdl()`

https://github.com/logisim-evolution/logisim-evolution/blob/master/src/main/java/com/cburch/logisim/fpga/hdlgenerator/Hdl.java#L39-L45

**Comment by maehne** [comment] 2022-03-28 12:51
@quick0831: I agree with your proposed fix. Could you please make a PR?

**Comment by BFH-ktt1** [comment] 2022-08-31 14:21
Closing, as PR was merged

**Closed by BFH-ktt1** 2022-08-31 14:21 UTC
Labels: bug, investigating
