### ISSUE TITLE
Endless rename

### ISSUE THREAD

**Issue by ogamespec** [logisim-evolution/logisim-evolution#1628] opened 2023-01-08 11:44 UTC
1. Set module name "xxx"
2. Set module label "yyy"
3. Ok
4. Set module label "xxx"
5. Endless loop of errors

![image](https://user-images.githubusercontent.com/5828819/211194337-7b0af9d9-5feb-4070-a8a3-a2d44a7bdf7f.png)

![image](https://user-images.githubusercontent.com/5828819/211194340-35790409-c238-4b73-957e-66335f4dfdb4.png)

**Comment by maehne** [comment] 2023-01-10 08:19
What version of Logisim-evolution are you using? I cannot reproduce this behaviour with [version 3.8.0](https://github.com/logisim-evolution/logisim-evolution/releases/tag/v3.8.0). Instead, I get a clear error message:

![grafik](https://user-images.githubusercontent.com/1174243/211496697-b6c1d045-568d-46ae-83fb-c304e7396d72.png)

Please check if the error on your side persists with the most recent version and if so, please provide more detailed steps how to reproduce the issue on our side. For the moment, I will close this issue. Feel free to reopen it to provide more details.

**Closed by maehne** 2023-01-10 08:19 UTC
Labels: invalid
