### ISSUE TITLE
Font size too large in the canvas

### ISSUE THREAD

**Issue by dxhisboy** [logisim-evolution/logisim-evolution#1452] opened 2022-05-04 05:42 UTC
I'm not sure about if it was a system configuration problem on my computer. Most of my computers runs Archlinux with Java 18. It seems the pin text of RAM is too large and overlaps each other:
![image](https://user-images.githubusercontent.com/3888709/166627907-879028c8-150e-4e8b-b46f-4f3bec20eee2.png)

While I didn't found a way to configure font of the canvas in menus. I found that a modification in `InstancePainter` work:
```
  public InstancePainter(ComponentDrawContext context, InstanceComponent instance) {
    this.context = context;
    this.comp = instance;
    this.context.getGraphics().setFont(new Font("monospaced", Font.PLAIN, 12)); // added this line
  }
```
Is there a way to configure the font settings in a graphical way?

**Comment by maehne** [comment] 2022-05-05 13:17
Thanks for reporting the issue and proposing a fix! To understand better the cause of the issue, could you please answer the following questions?

- Does this problem occur by any chance on a high-resolution (4K) screen? 

- Do you have any zoom configured for the screen in your desktop environment? 

- Does it help to set the "zoom factor" to 1.0 in File -> Preferences... -> Window?

**Comment by dxhisboy** [comment] 2022-05-06 06:05
> * Does this problem occur by any chance on a high-resolution (4K) screen?

Screen: 4K, 32 inch (should not configure scale at that PPI)

> * Do you have any zoom configured for the screen in your desktop environment?

Desktop environment: GNOME 42 on Wayland, no scale configured.


> * Does it help to set the "zoom factor" to 1.0 in File -> Preferences... -> Window?

I've tried, it only scales text in the component selection panel at left and several other GUI parts. The font in the circuit canvas keeps unchanged.

**Comment by dxhisboy** [comment] 2022-05-06 06:37
And I also reproduced the problem on another screen, which is faked to be at 96 PPI.
![image](https://user-images.githubusercontent.com/3888709/167079440-63bbb51c-1f81-4877-bbd5-3d3c4843e46f.png)

![image](https://user-images.githubusercontent.com/3888709/167079613-e9256fd6-1b10-4b2d-856b-9cc3c8efc2aa.png)

xrandr output:
```
Screen 0: minimum 16 x 16, current 2560 x 1600, maximum 32767 x 32767
XWAYLAND0 connected primary 2560x1600+0+0 (normal left inverted right x axis y axis) 580mm x 360mm
```

**Comment by fi11222** [comment] 2022-07-31 06:47
@dxhisboy Could you tell me where to put the code you showed to fix the problem. I am using Ubuntu 20.04.4 LTS.

Thanks

**Comment by 3vi1** [comment] 2022-08-11 23:35
I see this same thing.  The entire interface, menus and all appears to be at 2x zoom when the preferences are set to 1x, and there doesn't appear to be any way to scale down beyond that.  This is on Plasma (x11) desktop on Ubuntu 22.10 (Kinetic Kudu beta), using a 2560x1440 screen with no desktop scaling.

**Comment by dxhisboy** [comment] 2022-10-07 13:14
> @dxhisboy Could you tell me where to put the code you showed to fix the problem. I am using Ubuntu 20.04.4 LTS.
> 
> Thanks

I almost forget it, but I think the class name is correct, just use grep or other searching tools to locate the constructor of InstancePainter.

**Comment by LAPSyLAB** [comment] 2022-10-16 07:16
Hello,

have the same problem on 2550x1600 resolution. Have changed Windows system settings for Fonts size (from 175% to 150%),
restarted Logisim Evo and it helped... 
![image](https://user-images.githubusercontent.com/11449283/196023316-a705c021-ea24-47c3-97d4-337770270477.png)

**Comment by jimmy-zx** [comment] 2023-03-12 03:55
Seems like the workaround will cause poking not to work, with the following report

> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.Graphics.setFont(java.awt.Font)" because the return value of "com.cburch.logisim.comp.ComponentDrawContext.getGraphics()" is null

Adding a check before setFont would resolve this
```
if (this.context.getGraphics() != null) {
  this.context.getGraphics().setFont(new Font("monospaced", Font.PLAIN, 12));
}
```

**Comment by lucianchauvin** [comment] 2024-02-27 14:33
Hello. I am still having this issue and am not sure what the fix is?

**Comment by maehne** [comment] 2024-05-16 09:07
@lucianchauvin, @jimmy-zx, @LAPSyLAB, @dxhisboy, @3vi1, @fi11222: Could you please check with the [latest nightly build](https://github.com/logisim-evolution/logisim-evolution/actions/runs/9104282361) whether this issue persists? Please, use one of the native packages, which bundle JDK 21 instead of launching the JAR file directly with a potentially out-dated JRE installed via your operating system's package manager.

**Comment by 3vi1** [comment] 2024-05-19 14:35
Looks much better now.  Tested with the AMD64 deb on an Ubuntu 24.10 (devel repos) base running Plasma 6.1 compiled from source.  Problem is fixed for me.

**Comment by maehne** [comment] 2024-05-20 15:44
@3vi1: Thanks for the feedback. I therefore close this issue as fixed.

@lucianchauvin, @jimmy-zx, @LAPSyLAB, @dxhisboy, @fi11222: Feel free to reopen in case the issue isn't resolved for you with the [latest nightly build](https://github.com/logisim-evolution/logisim-evolution/actions/runs/9104282361).

**Closed by maehne** 2024-05-20 15:44 UTC
Labels: bug, help wanted, pri std, good first issue

**Comment by Poly-Mentor** [comment] 2026-08-09 22:12
Hi, I have the same problem on Ubuntu 26.04 LTS with 2880x1620 display and system scaling set to 166%
I've tried different packages: snap, flatpak, latest jar release, and the problem was identical in each one - UI scales nicely, even without changing default zoom factor the size is reasonable, but font on in-canvas components is too big, no matter what zoom factor is set:

<img width="2038" height="1378" alt="Image" src="https://github.com/user-attachments/assets/c481b30f-7be6-44fe-b940-8d97c3047c46" />

```bash
$ java --version
openjdk 25.0.3 2026-04-21
OpenJDK Runtime Environment (build 25.0.3+9-2-26.04.2-Ubuntu)
OpenJDK 64-Bit Server VM (build 25.0.3+9-2-26.04.2-Ubuntu, mixed mode, sharing)
```

I'd be grateful for any help with this issue.

**Comment by maehne** [comment] 2026-08-21 12:43
@Poly-Mentor: Please check with our [Nightly builds](https://github.com/logisim-evolution/logisim-evolution#nightly-builds). The issue should be fixed.
