### ISSUE TITLE
Feature Request: DAC Mode for Buzzer

### ISSUE THREAD

**Issue by OfficialPixelBrush** [logisim-evolution/logisim-evolution#1746] opened 2023-05-04 08:12 UTC
It would be incredibly useful to pipe binary Data directly into a Buzzer and have it be played back at the appropriate amplitude, allowing for bit-driven Audio, akin to that of a simple R2R DAC.

Only downside of this would be that it'd be simulation speed dependent.

**Comment by juli-99** [comment] 2023-05-04 10:08
Possibly a duplicate of #1627.

**Comment by maehne** [comment] 2023-05-04 13:55
I agree with @juli-99 that this is a duplicate of #1627 and close it as not planned. PRs in this direction are welcome, but it is not a priority for us.

**Closed by maehne** 2023-05-04 13:55 UTC
Labels: duplicate
