### ISSUE TITLE
Multiplexer in Verilog

### ISSUE THREAD

**Issue by EmperorPenguin18** [logisim-evolution/logisim-evolution#1426] opened 2022-03-31 23:04 UTC
When I synthesize to verilog, Multiplexer_2.v uses a variable called nrOfBits, but that variable doesn't exist.

**Comment by maehne** [comment] 2022-04-01 07:06
Thanks for reporting! The HDL code generation underwent last year a substantial reimplementation and, unfortunately, introduced some smaller bugs. On the VHDL side, these were found relatively quickly, but Verilog is used less on our side.

**Comment by BFH-ktt1** [comment] 2022-04-04 06:28
@EmperorPenguin18 , I confirm this bug, thanks for the report!

**Comment by BFH-ktt1** [comment] 2022-04-05 04:55
Please try the nightly build to see if the problem is fixed. Closing for now, please reopen when the problem persists.

**Closed by BFH-ktt1** 2022-04-05 04:55 UTC
Labels: bug, pri +1, investigating, all OS, good first issue
