### ISSUE TITLE
seven segment led doesnt fully work. v3.9.0

### ISSUE THREAD

**Issue by PristineWolf** [logisim-evolution/logisim-evolution#2086] opened 2024-10-30 10:23 UTC
hello.. I'm not sure if this is an issue only for me but I just downloaded the latest version (3.9.0) and when I use the dip switch (8bits to power) a seven segment display, all pins work except for the first two (a, b) which doesnt turn on when given power. hoping to hear back from someone on this. thank you
edit: I just tried it again and I'm not sure how but its now working :/

**Comment by maehne** [comment] 2024-11-04 08:07
Closing as resolved due to your edit. Reopen and attach a reproducer in form of a CIRC file inside a ZIP archive should you observe again the issue.

**Closed by maehne** 2024-11-04 08:07 UTC
