### ISSUE TITLE
Add hot keys for Project menu's Move Up & Move Down options

### ISSUE THREAD

**Issue by prlaba** [logisim-evolution/logisim-evolution#1807] opened 2023-07-31 12:52 UTC
Please consider adding hot keys for the Project menu's _Move Up_ and _Move Down_ options.

It's tedious to have to reopen the menu and click on the option to move a circuit up or down one position, especially if the circuit has to be moved up or down many positions.

**Comment by gtxzsxxk** [comment] 2023-07-31 14:20
I'm working on the hotkeys these days: #1802 . If merged, users can edit the hotkeys in a preference Tab. But in my PR, I haven't consider the default key bindings for _Move up_ and _Move Down_. Do you have any candidates for them?

**Comment by prlaba** [comment] 2023-08-01 15:28
Hmm…. I hadn’t thought about specific hotkeys for those options.

How about Ctrl+U for Move Circuit Up and Ctrl+D for Move Circuit Down?  Are they already in use?

Paul

**Comment by prlaba** [comment] 2023-08-03 06:00
Yes, after I sent those suggestions I saw that Ctrl+D was already assigned.

Sure, Shift+U and Shift+D would work.

You’re planning to make the hotkeys editable?  That’s great!

Thanks,

Paul

**Comment by davidhutchens** [comment] 2023-08-17 01:03
@prlaba: With the merger of #1802, shortcuts for these actions should be implemented with ctrl-shift-U and ctrl-shift-D in the main branch. Please check our Nightly build, or build yourself from main.

I am closing this as completed. Please reopen if the issue is not solved.

**Closed by davidhutchens** 2023-08-17 01:03 UTC

**Comment by prlaba** [comment] 2023-08-17 02:13
Thank you!

Paul
